package theme.color

import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.TextUnit
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

val size: AntdSize =
    AntdSize(
        fontSize = 14.sp,
        fontSizeSM = 12.sp,
        fontSizeLG = 16.sp,
        fontSizeXL = 20.sp,
        fontSizeHeading1 = 38.sp,
        fontSizeHeading2 = 30.sp,
        fontSizeHeading3 = 24.sp,
        fontSizeHeading4 = 20.sp,
        fontSizeHeading5 = 26.sp,
        lineHeight = 1.571.dp,
        lineHeightSM = 1.666.dp,
        lineHeightLG = 1.5.dp,
        lineHeightHeading1 = 1.21.dp,
        lineHeightHeading2 = 1.266.dp,
        lineHeightHeading3 = 1.333.dp,
        lineHeightHeading4 = 1.4.dp,
        lineHeightHeading5 = 1.5.dp,
        margin = 16.dp,
        marginXXS = 4.dp,
        marginXS = 8.dp,
        marginSM = 12.dp,
        marginMD = 20.dp,
        marginLG = 24.dp,
        marginXL = 32.dp,
        marginXXL = 48.dp,
        padding = 16.dp,
        paddingXXS = 4.dp,
        paddingXS = 8.dp,
        paddingSM = 12.dp,
        paddingMD = 20.dp,
        paddingLG = 24.dp,
        paddingXL = 32.dp,
        borderRadius = 6.dp,
        borderRadiusXS = 2.dp,
        borderRadiusSM = 4.dp,
        borderRadiusLG = 8.dp,
    )

data class AntdSize(
    val fontSize: TextUnit,
    val fontSizeSM: TextUnit,
    val fontSizeLG: TextUnit,
    val fontSizeXL: TextUnit,
    val fontSizeHeading1: TextUnit,
    val fontSizeHeading2: TextUnit,
    val fontSizeHeading3: TextUnit,
    val fontSizeHeading4: TextUnit,
    val fontSizeHeading5: TextUnit,
    val lineHeight: Dp,
    val lineHeightSM: Dp,
    val lineHeightLG: Dp,
    val lineHeightHeading1: Dp,
    val lineHeightHeading2: Dp,
    val lineHeightHeading3: Dp,
    val lineHeightHeading4: Dp,
    val lineHeightHeading5: Dp,
    val margin: Dp,
    val marginXXS: Dp,
    val marginXS: Dp,
    val marginSM: Dp,
    val marginMD: Dp,
    val marginLG: Dp,
    val marginXL: Dp,
    val marginXXL: Dp,
    val padding: Dp,
    val paddingXXS: Dp,
    val paddingXS: Dp,
    val paddingSM: Dp,
    val paddingMD: Dp,
    val paddingLG: Dp,
    val paddingXL: Dp,
    val borderRadius: Dp,
    val borderRadiusXS: Dp,
    val borderRadiusSM: Dp,
    val borderRadiusLG: Dp
)